trilioData/triliovault-cfg-scripts

- juju-charms/TODO.txt
- juju-charms/charm-trilio-horizon-plugin/src/config.yaml
- juju-charms/charm-trilio-horizon-plugin/src/metadata.yaml
- juju-charms/charm-trilio-horizon-plugin/src/old
- juju-charms/charm-trilio-horizon-plugin/src/reactive/trilio_horizon_plugin.py
- juju-charms/charm-trilio-horizon-plugin/test-requirements.txt
- juju-charms/charm-trilio-horizon-plugin/tox.ini
- juju-charms/charm-trilio-horizon-plugin/unit_tests/test_horizon_plugin.py
1. Added basic unit tests using tox
2. Removed config parameter for tvault version
3. Fetching tvault version from the appliance using get_version function
4. Updated config variable names, return values
> Updated Horizon Plugin charm with unit tests and changes in reactive handlers

- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile
- redhat-director-scripts/docker/trilio-horizon-plugin/build_container.sh
- redhat-director-scripts/docker/trilio-horizon-plugin/kolla_build_container.sh
@deepanshusagar : Please review. We need to add one more container to build process i.e horizon container. You can use build container script.
> Added dockerfile to create horizon container

- ansible/environments/group_vars/all/vars.yml
- ansible/roles/ansible-datamover-api/tasks/uninstall.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/get_openstack_version.yml
datmover variable's strings is diffrent in vars.yml and in playbook. so undefined variable error comes (TVAULT-2729)
1. changed variable name in vars.yml
2. Added code to use queens virtual env for pike/quuens setup.
> Fixed TVAULT-2729 and added code to use queens virtual env

- juju-charms/charm-trilio-data-mover-api/src/config.yaml
- juju-charms/charm-trilio-data-mover-api/src/lib/charm/openstack/dmapi.py
- Now the user can modify the port values with a single command(juju config)
> Provision to modify default port addresses

- ansible/environments/group_vars/all/vars.yml
- ansible/roles/ansible-tvault-contego-extension/templates/nfs.conf.j2
- ansible/roles/ansible-tvault-contego-extension/templates/s3_amazon.conf.j2
- ansible/roles/ansible-tvault-contego-extension/templates/s3_ceph.conf.j2
- ansible/roles/ansible-tvault-contego-extension/templates/s3_minio.conf.j2
- ansible/roles/ansible-tvault-contego-extension/templates/swift.conf.j2
Fix : added code in contego conf to execute privsep binary.
@shyam-biradar , @abhijeetpatra , @rajneeshkapoor , @sachin-trilio Please review.
> fixed TVAULT-2670 in ansible

- juju-charms/charm-trilio-data-mover-api/src/lib/charm/openstack/dmapi.py
- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
- juju-charms/charm-trilio-data-mover/unit_tests/test_data_mover.py
- Added privsep and conductor entries in conf file 
- Application version for data-mover.
> Data-mover changes

- ansible/roles/ansible-datamover-api/tasks/install_on_queens.yml
added code "allow_unauthenticated :yes " for ubutnu16 in ansible. 
@shyam-biradar , @abhijeetpatra , @rajneeshkapoor , @sachin-trilio Please review.
> added code "allow_unatuhenticated" for Ubuntu16

- ansible/roles/ansible-datamover-api/tasks/install_on_queens.yml
- ansible/roles/ansible-datamover-api/tasks/uninstall.yml
**Fix** : disabled and stopped tvault-datamover-api service in uninstalltion scripts. and removed service file.
@abhijeetpatra , @shyam-biradar , @MuralidharB , @rajneeshkapoor , @sachin-trilio Please review.
> Fixed TVAULT-2776

- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
- The service requires restart after it exits with success or failure status.
> Resolves datamover service restart issue.

- ansible/README.md
- ansible/roles/ansible-datamover-api/tasks/install_on_queens.yml
1.added code to update pacakage repositories depending on distribution.
2.updated README.md as tagname given in README.md to uninstall horizon plugin was not correct.
@shyam-biradar , @abhijeetpatra , @MuralidharB Please review.
> TVAULT-2801 added code to update pacakage repositories depending on distribution

- dmapi_install_steps.rst
- horizon_install_steps.rst
Documented deployment steps in horizon_install_steps.rst file
@MuralidharB , @shyam-biradar , @rajneeshkapoor , @sachin-trilio , @abhijeetpatra  Please review
> deployment document to install horizon plugin

- juju-charms/charm-trilio-data-mover-api/src/templates/dmapi.conf
- Added 'insecure' option in the template file.
- Added/modified 'debug' , 'Region Name' and 'ca_file' as well.
> Issue #130

- juju-charms/charm-trilio-configurator/.testr.conf
- juju-charms/charm-trilio-configurator/src/layer.yaml
- This file is required for unit testing.
> Added missing file

- juju-charms/charm-trilio-configurator/src/config.yaml
- juju-charms/charm-trilio-configurator/unit_tests/test_configurator.py
Updated config file to remove charm proof errors.
Updated unit test
> Updated config file, unit test

- ansible/environments/group_vars/all/vars.yml
Removed passowrd from vars.yml.
@savitha-p , @rajneeshkapoor , @sachin-trilio  Please reivew.
> removed password from vars.yml

- juju-charms/charm-trilio-horizon-plugin/src/reactive/trilio_horizon_plugin.py
Added function to copy dashboard HTML template if provided by user
> Added function to copy dashboard HTML template if provided by user

- juju-charms/charm-trilio-data-mover-api/.stestr.conf
- juju-charms/charm-trilio-data-mover-api/.testr.conf
- juju-charms/charm-trilio-data-mover/.stestr.conf
- juju-charms/charm-trilio-data-mover/.testr.conf
- juju-charms/charm-trilio-data-mover/src/files/trilio/trilio.filters
- juju-charms/charm-trilio-data-mover/src/files/trilio/trilio_sudoers
- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
- juju-charms/charm-trilio-data-mover/tox.ini
- juju-charms/charm-trilio-horizon-plugin/.stestr.conf
- juju-charms/charm-trilio-horizon-plugin/.testr.conf
- juju-charms/charm-trilio-horizon-plugin/src/reactive/trilio_horizon_plugin.py
- juju-charms/charm-trilio-horizon-plugin/tox.ini
- juju-charms/charm-trilio-horizon-plugin/unit_tests/test_horizon_plugin.py
> Changes for 3.2

- juju-charms/charm-trilio-data-mover-api/src/templates/dmapi.conf
Adding oslo_messaging_rabbit section from templates
> Added oslo_messaging_rabbit section

- juju-charms/charm-trilio-horizon-plugin/src/files/trilio/trilio-horizon-plugin.html
This resolves a display issue with the Admin->Backups Admin dashboard
in horizon.  Addresses Issue 174
> Updated trilio-horizon-plugin.html template

- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
- juju-charms/charm-trilio-horizon-plugin/src/reactive/trilio_horizon_plugin.py
Changes in data mover uninstall for py2 venv
Update in horizon plugin for upgrade
> Changes in data mover uninstall for py2 venv

- juju-charms/charm-trilio-data-mover/src/files/trilio/get_pkgs.py
- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
Changes in data mover for retrieving contego path and install options
> Changes in data mover for retrieving contego path and install options

- ansible/roles/ansible-datamover-api/tasks/install_ubuntu.yml
- ansible/roles/ansible-datamover-api/templates/trilio.repo
- ansible/roles/ansible-horizon-plugin/tasks/install_ubuntu.yml
- ansible/roles/ansible-horizon-plugin/templates/trilio.repo
- ansible/roles/ansible-tvault-contego-extension/tasks/create_filter.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/install_ubuntu.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/post_install.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/uninstall_ubuntu.yml
- ansible/roles/ansible-tvault-contego-extension/templates/nova.j2
- ansible/roles/ansible-tvault-contego-extension/templates/trilio.repo
@yogeshrathoret15 , @savitha-p , @rajneeshkapoor , @abhijeetpatra   Please review
> TVAULT-3187 - added changes in ansiblle

- juju-charms/charm-trilio-data-mover-api/src/reactive/dmapi_handlers.py
- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
- juju-charms/charm-trilio-data-mover/unit_tests/test_data_mover.py
Fixed issues faced during 3.2 to 3.3 upgrade in dmapi and data mover charms. Also fixed unit test for datamover.
> Fixing issues in upgrade for dmapi and datamover

- ansible/roles/ansible-datamover-api/tasks/install_ubuntu.yml
- ansible/roles/ansible-horizon-plugin/tasks/install_ubuntu.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/install_ubuntu.yml
@rajneeshkapoor , @abhijeetpatra , @savitha-p  Please review
> Fixed TVAULT-3187

- ansible/roles/ansible-tvault-contego-extension/templates/objstore_service.j2
- ansible/roles/ansible-tvault-contego-extension/templates/objstore_service_debian.j2
@savitha-p , @rajneeshkapoor , @sachin-trilio  Please review
> Fixed TVAULT-3271

- ansible/roles/ansible-datamover-api/tasks/install_ubuntu.yml
- ansible/roles/ansible-horizon-plugin/tasks/install_ubuntu.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/install_ubuntu.yml
- ansible/roles/ansible-tvault-contego-extension/templates/objstore_service.j2
@rajneeshkapoor , @abhijeetpatra , @savitha-p Please review
> Fixed TVAULT-3187,TVAULT-3271

- ansible/roles/ansible-tvault-contego-extension/templates/contego_service.j2
- ansible/roles/ansible-tvault-contego-extension/templates/contego_service_s3.j2
@abhijeetpatra , @savitha-p , @rajneeshkapoor , @sachin-trilio Please review
> Fixed TVAULT-3234 in ansible deployment

- redhat-director-scripts/docker/build_containers.sh
- redhat-director-scripts/docker/trilio-datamover-api/Dockerfile_rhosp14
- redhat-director-scripts/docker/trilio-datamover-api/Dockerfile_tripleorocky
- redhat-director-scripts/docker/trilio-datamover/Dockerfile_rhosp14
- redhat-director-scripts/docker/trilio-datamover/Dockerfile_tripleorocky
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp14
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_tripleorocky
Added code to build rhosp14 and tripleo rocky containers.
> Tvault 3467

- juju-charms/build.sh
- juju-charms/charm-trilio-data-mover-api/src/config.yaml
- juju-charms/charm-trilio-data-mover-api/src/metadata.yaml
- juju-charms/charm-trilio-data-mover-api/src/reactive/dmapi_handlers.py
- juju-charms/charm-trilio-data-mover-api/tox.ini
- juju-charms/charm-trilio-data-mover/src/config.yaml
- juju-charms/charm-trilio-data-mover/src/files/trilio/get_nova_conf.py
- juju-charms/charm-trilio-data-mover/src/metadata.yaml
- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
- juju-charms/charm-trilio-data-mover/tox.ini
- juju-charms/charm-trilio-horizon-plugin/src/config.yaml
- juju-charms/charm-trilio-horizon-plugin/src/metadata.yaml
- juju-charms/charm-trilio-horizon-plugin/tox.ini
- And also handling python2 deprecation
> Fixes related to nova.conf file location

- juju-charms/charm-trilio-horizon-plugin/src/files/trilio/sync_static.py
TVAULT-3520: Fixed indentation issue in horizon-plugin sync_static.py
> TVAULT-3520: Fixed indentation issue in horizon-plugin sync_static.py

- juju-charms/charm-trilio-data-mover-api/src/reactive/dmapi_handlers.py
- juju-charms/charm-trilio-data-mover/src/files/trilio/trilio.filters
- juju-charms/charm-trilio-data-mover/src/files/trilio/trilio_sudoers
- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
- We ll use the default nova sudoers permission
> TVAULT-3572: avoiding our own nova sudoers entry

- juju-charms/charm-trilio-data-mover-api/src/config.yaml
- juju-charms/charm-trilio-data-mover-api/src/metadata.yaml
- juju-charms/charm-trilio-data-mover-api/unit_tests/test_dmapi_handlers.py
- juju-charms/charm-trilio-data-mover/src/config.yaml
- juju-charms/charm-trilio-data-mover/src/metadata.yaml
- juju-charms/charm-trilio-horizon-plugin/src/config.yaml
- juju-charms/charm-trilio-horizon-plugin/src/files/trilio/trilio-horizon-plugin.html
- juju-charms/charm-trilio-horizon-plugin/src/metadata.yaml
> Changes in charms for TVM 4.0

- redhat-director-scripts/docker/build_containers.sh
@shyam-biradar @savitha-afour @dhiraj-trilio please review this
> rhosp13 container creation fix

- redhat-director-scripts/docker/build_rhosp16_containers.sh
@shyam-biradar @savitha-p @dhiraj-trilio please review this
> podman push issue fix

- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
Data Mover helper cmd change
Set user_virt_qemu = False
> Data Mover helper cmd change

- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp13
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp14
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_tripleorocky
- tripleo-scripts/docker/trilio-horizon-plugin/Dockerfile
@shyam-biradar @abhijeetpatra please review this
> TVAULT-3723 workloadmgrclient fixed

- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp13
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp14
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_tripleorocky
- tripleo-scripts/docker/trilio-horizon-plugin/Dockerfile
@shyam-biradar @abhijeetpatra please review this
> TVAULT-3723 workloadmgrclient fix

- juju-charms/charm-trilio-data-mover-api/unit_tests/test_charm_openstack_dmapi.py
Fixed Unit Tests for DMAPI after mysql port issue fix
> Fixed DMAPI Unit Tests

- kolla-ansible/trilio-datamover-api/trilio.list
- kolla-ansible/trilio-datamover-api/trilio.repo
- kolla-ansible/trilio-datamover/trilio.list
- kolla-ansible/trilio-datamover/trilio.repo
- redhat-director-scripts/docker/trilio-datamover-api/trilio.repo
- redhat-director-scripts/docker/trilio-datamover/trilio.repo
- redhat-director-scripts/docker/trilio-horizon-plugin/trilio.repo
@rajneeshkapoor could you please merge this?
> TVAULT-3806 repo changes for 4.0-patch

- redhat-director-scripts/puppet/trilio/files/s3-cert.pem
- redhat-director-scripts/puppet/trilio/manifests/contego/config.pp
- redhat-director-scripts/puppet5/trilio/files/s3-cert.pem
- redhat-director-scripts/puppet5/trilio/manifests/contego/config.pp
Added code to copy pem file to all compute nodes.
> V4.0maintenance TVAULT-3812 - remaining changes

- juju-charms/charm-trilio-data-mover/src/config.yaml
- juju-charms/charm-trilio-data-mover/src/files/trilio/trilio.filters
- juju-charms/charm-trilio-data-mover/src/metadata.yaml
- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
Added support for multiple nfs shares in Data Mover charm
> TVAULT-3827 : Added support for multiple nfs shares in Data Mover charm

- kolla-ansible/trilio-datamover-api/Dockerfile_ussuri_centos
- kolla-ansible/trilio-datamover/Dockerfile_ussuri_centos
Added changes to deploy docker container on ussuri release for CentOS 8
> Added changes for CentOS8

- kolla-ansible/trilio-horizon-plugin/trilio.list
- kolla-ansible/trilio-horizon-plugin/trilio.repo
@shyam-biradar @savitha-afour @dhiraj-trilio @DeepikaAFour @abhijeetpatra could you please review this
> repo change for trilio-horizo-plugin kolla-ansible

- kolla-ansible/ansible/roles/triliovault/defaults/main.yml
- kolla-ansible/ansible/roles/triliovault/tasks/bootstrap.yml
- kolla-ansible/ansible/roles/triliovault/tasks/bootstrap_service.yml
- kolla-ansible/ansible/roles/triliovault/tasks/config.yml
- kolla-ansible/ansible/roles/triliovault/tasks/deploy.yml
- kolla-ansible/ansible/roles/triliovault/tasks/rabbitmq.yml
- kolla-ansible/trilio-datamover-api/Dockerfile_ussuri_centos
- kolla-ansible/trilio-datamover-api/Dockerfile_ussuri_ubuntu
1. Added code to create database user and database for dmapi
2. Added code to create rabbitmq user for dmapi
> database and rabbitmq changes for dmapi

- kolla-ansible/ansible/roles/triliovault/defaults/main.yml
- kolla-ansible/ansible/roles/triliovault/templates/triliovault-datamover-api.conf.j2
- As part of dmapi independency effort, updated dmapi.conf template
> dmapi conf file changes

- kolla-ansible/trilio-datamover-api/Dockerfile_ussuri_centos
@shyam-biradar @abhijeetpatra @DeepikaAFour @dhiraj-trilio could you please review this
> TVAULT-3902 missing ownership for /var/cache/dmapi

- kolla-ansible/ansible/roles/triliovault/defaults/main.yml
- kolla-ansible/ansible/triliovault_globals.yml
updated code to take docker images from dynamically assigned docker hub or local server details
> dynamic docker registry hub

- redhat-director-scripts/docker/build_rhosp16.1_containers.sh
- redhat-director-scripts/docker/trilio-datamover-api/Dockerfile_rhosp16.1
- redhat-director-scripts/docker/trilio-datamover/Dockerfile_rhosp16.1
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp16.1
-- Containers already published.
-- This PR contains dockerfiles and build script.
> TVAULT-3968

- ansible/environments/group_vars/all/vars.yml
- ansible/roles/ansible-datamover-api/tasks/get_dmapi_ssl_cert.yml
- ansible/roles/ansible-datamover-api/tasks/get_rabbitmq_ssl_cert.yml
- ansible/roles/ansible-datamover-api/tasks/main.yml
- ansible/roles/ansible-datamover-api/templates/datamover_url
- ansible/roles/ansible-horizon-plugin/tasks/uninstall_rhel.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/create_contego_conf.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/object_store_service.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/post_uninstall.yml
- ansible/roles/ansible-tvault-contego-extension/templates/tvault-contego.conf.j2
- ansible/roles/ansible-tvault-contego-extension/templates/tvault-object-store.conf.j2
PR raised for below jira's, please review
TVAULT- 4007 : [OSA Ubuntu20 Ussuri] Trilio component deployment failed using ansible scripts
TVAULT-4002: [OSA Ussuri] S3, Rabbitmq and Dmapi SSl certificate should be available when ssl is enabled
> TVAULT-4002: [OSA Ussuri] S3, Rabbitmq and Dmapi SSl certificate should be available when ssl is enabled

- kolla-ansible/trilio-horizon-plugin/Dockerfile_ussuri_centos
@abhijeetpatra @shyam-biradar @DeepikaAFour @dhiraj-trilio @savitha-afour could you please review this
> TVAULT-4018 kolla centos container creation failing due to disabled epel repo required for python3-configargparse 

- ansible/roles/ansible-horizon-plugin/files/sync_static1.py
- juju-charms/charm-trilio-data-mover-api/src/reactive/dmapi_handlers.py
- juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py
- juju-charms/charm-trilio-horizon-plugin/src/reactive/trilio_horizon_plugin.py
- python2 compatibility for finding executable full path
> TVAULT-4096: trilio-cfg-script repo Bandit security issues resolved

- kolla-ansible/ansible/roles/triliovault/templates/triliovault-datamover.conf.j2
- kolla-ansible/ansible/triliovault_globals.yml
- Tested deployment on kolla ussuri.
> Tvault4159 kolla

- redhat-director-scripts/docker/trilio-datamover-api/Dockerfile_rhosp13
- redhat-director-scripts/docker/trilio-datamover-api/Dockerfile_rhosp16
- redhat-director-scripts/docker/trilio-datamover-api/Dockerfile_rhosp16.1
- redhat-director-scripts/docker/trilio-datamover/Dockerfile_rhosp13
- redhat-director-scripts/docker/trilio-datamover/Dockerfile_rhosp16
- redhat-director-scripts/docker/trilio-datamover/Dockerfile_rhosp16.1
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp13
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp16
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp16.1
-- Added command to install security packages by Redhat. This is needed for vulnerability test to pass which is part of redhat certification.
> Fixes needed for redhat certification

- redhat-director-scripts/rhosp13/environments/trilio_env.yaml
- redhat-director-scripts/rhosp13/puppet/trilio/manifests/dmapi.pp
- redhat-director-scripts/rhosp13/puppet/trilio/templates/dmapi.erb
- redhat-director-scripts/rhosp13/services/trilio-datamover-api.yaml
- redhat-director-scripts/rhosp16.1/environments/trilio_env.yaml
- redhat-director-scripts/rhosp16.1/puppet/trilio/manifests/dmapi.pp
- redhat-director-scripts/rhosp16.1/puppet/trilio/templates/dmapi.erb
- redhat-director-scripts/rhosp16.1/services/trilio-datamover-api.yaml
- redhat-director-scripts/rhosp16/environments/trilio_env.yaml
- redhat-director-scripts/rhosp16/puppet/trilio/manifests/dmapi.pp
- redhat-director-scripts/rhosp16/puppet/trilio/templates/dmapi.erb
- redhat-director-scripts/rhosp16/services/trilio-datamover-api.yaml
-- Fixed for RHOSP13, RHOSP16, RHOSP16.1
> Tv4228 -Added code to make dapi_workers parameter configurable

- kolla-ansible/ansible/roles/triliovault/templates/triliovault-datamover-api.conf.j2
- kolla-ansible/ansible/triliovault_globals.yml
Added a fix that the user can define the dmapi_workers count.
Specify the dmapi_workers count and run deploy cmd.
> Fix for TVAULT-4228

- redhat-director-scripts/rhosp16.1/environments/trilio_env.yaml
- redhat-director-scripts/rhosp16.1/puppet/trilio/manifests/contego.pp
- redhat-director-scripts/rhosp16.1/services/trilio-datamover.yaml
Reverts trilioData/triliovault-cfg-scripts#436
> Revert "TVAULT-3931 Changed datamover mount point"

- redhat-director-scripts/rhosp16.1/environments/trilio_env.yaml
- redhat-director-scripts/rhosp16.1/puppet/trilio/manifests/contego.pp
- redhat-director-scripts/rhosp16.1/services/trilio-datamover.yaml
Reverts trilioData/triliovault-cfg-scripts#437
> Revert "TVAULT-3931 master : changed datamover mount point"

- redhat-director-scripts/rhosp13/services/trilio-datamover-api.yaml
- redhat-director-scripts/rhosp16.1/services/trilio-datamover-api.yaml
- redhat-director-scripts/rhosp16/services/trilio-datamover-api.yaml
- Added fix for RHOSP13, RHOSP16, RHOSP16.1
- Tested deployment on RHOSP13 and RHOSP16.1
> TVAULT-4339 -- Added haproxy timeouts for dmapi service

- kolla-ansible/ansible/roles/triliovault/defaults/main.yml
- kolla-ansible/ansible/roles/triliovault/templates/triliovault-datamover.conf.j2
- kolla-ansible/ansible/roles/triliovault/templates/triliovault-datamover.json.j2
- kolla-ansible/ansible/triliovault_globals.yml
Kolla Ansible script should be in sync with TVO UI
Storage Backend type.
> Tvault 4118 kolla ansible script should be in sync with TVO UI for storage backend type

- kolla-ansible/build_containers.sh
- redhat-director-scripts/docker/build_rhosp13_containers.sh
- redhat-director-scripts/docker/build_rhosp16_containers.sh
@abhijeetpatra @savitha-p @shyam-biradar  could you please review this
> TVAULT-4502 Pull latest container images

- ansible/roles/ansible-datamover-api/tasks/set_database_variables.yml
> TVAULT-4515: [Victoria Qualification] Trilio component deployment failed on OSA CentOS8 Victoria

- kolla-ansible/build_containers.sh
@savitha-p could you please review this
> TVAULT-4517 dynamic openstack_release variable for kolla contianer

- kolla-ansible/publish_containers.sh
@savitha-p could you please review this
> TVAULT-4517 publish containers

- redhat-director-scripts/docker/build_tripleo_containers.sh
@shyam-biradar @savitha-p  could you please review this
> TVAULT-4577 delorean-component-tripleo.repo unable to reach

- common/generate_nfs_map.py
-- Executed pylint against the module
-- Fixed most of the linting issues.
> TVAULT-4589 linting fixes added

- common/triliovault_nfs_map_input.yml
- redhat-director-scripts/rhosp13/environments/trilio_env.yaml
- redhat-director-scripts/rhosp13/environments/trilio_nfs_map.yaml
- redhat-director-scripts/rhosp13/puppet/trilio/manifests/contego.pp
- redhat-director-scripts/rhosp13/puppet/trilio/templates/contego_nfs_conf.erb
- redhat-director-scripts/rhosp13/services/trilio-datamover.yaml
- redhat-director-scripts/rhosp16.1/environments/trilio_env.yaml
- redhat-director-scripts/rhosp16.1/environments/trilio_nfs_map.yaml
- redhat-director-scripts/rhosp16.1/puppet/trilio/manifests/contego.pp
- redhat-director-scripts/rhosp16.1/puppet/trilio/templates/contego_nfs_conf.erb
- redhat-director-scripts/tripleo-train/environments/trilio_nfs_map.yaml
- redhat-director-scripts/tripleo-train/puppet/trilio/manifests/contego.pp
- redhat-director-scripts/tripleo-train/puppet/trilio/templates/contego_nfs_conf.erb
- redhat-director-scripts/tripleo-train/services/trilio-datamover.yaml
-- Added multi-ip devops changes to rhosp13
-- Added multi-ip devops changes to tripleo train
> TVAULT-4590 TVAULT-4591 - rhosp13 and tripleo train changes

- redhat-director-scripts/docker/trilio-datamover-api/Dockerfile_tripleo_train_centos8
- redhat-director-scripts/docker/trilio-datamover/Dockerfile_tripleo_train_centos8
- redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_tripleo_train_centos8
@shyam-biradar could you please review this
> TVAULT-4618 TripleO container creation failure due to --no-stream flag

- ansible/roles/ansible-tvault-contego-extension/tasks/install_rhel.yml
https://triliodata.atlassian.net/wiki/spaces/TVO/pages/3257401345/draft+Ansible-tvault-contego+service+installation+fix+on+CentOS+RHEL
> TVAULT-4678 Fix added

- ansible/roles/ansible-tvault-contego-extension/tasks/install_rhel.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/install_ubuntu.yml
- ansible/roles/ansible-tvault-contego-extension/templates/modprobe-nbd.conf.j2
- ansible/roles/ansible-tvault-contego-extension/templates/module-load-nbd.conf.j2
Load nbd module before and after reboot of compute node(s)
> TVAULT-4710 create and load nbd driver

- ansible/roles/ansible-tvault-contego-extension/templates/trilio.filters.j2
Added  two filters one for nbd and other for rbd
- qemu-nbd: CommandFilter, qemu-nbd, root
- rbd: CommandFilter, rbd, root
> TVAULT-4722 updated the trilio.filters file to support nbd and rbd 

- redhat-director-scripts/docker/build_rhosp16_containers.sh
@abhijeetpatra  @shyam-biradar could you please review this
> TVAULT-4865 Add RHOSP16.2 container creation to automation

- redhat-director-scripts/docker/build_tripleo_containers.sh
- redhat-director-scripts/docker/publish_tripleo_containers.sh
@abhijeetpatra @savitha-p could you please review this
> TVAULT-4893 Removing tripleo centos8 container creation from automation

- redhat-director-scripts/docker/trilio-datamover/Dockerfile_rhosp13
- redhat-director-scripts/docker/trilio-datamover/Dockerfile_tripleo_train_centos7
@abhijeetpatra could you please review this
> TVAULT-4904 Snapshots are failing on python2 based Openstack setups

- redhat-director-scripts/rhosp13/puppet/trilio/manifests/horizon.pp
- redhat-director-scripts/rhosp16.1/puppet/trilio/manifests/horizon.pp
- redhat-director-scripts/rhosp16.2/puppet/trilio/manifests/horizon.pp
- redhat-director-scripts/tripleo-train/puppet/trilio/manifests/horizon.pp
- redhat-director-scripts/tripleo-wallaby/environments/trilio_env.yaml
- redhat-director-scripts/tripleo-wallaby/puppet/trilio/manifests/horizon.pp
- redhat-director-scripts/tripleo-wallaby/services/trilio-horizon.yaml
**Change log:** 
https://triliodata.atlassian.net/wiki/spaces/TL/pages/3411017729/TVAULT-4937+Overcloud+deploy+fails+with+TVO4.2
> TVAULT-4937 : Added default value for barbican_api_enabled parameter

- kolla-ansible/trilio-datamover-api/Dockerfile_ussuri_centos
- kolla-ansible/trilio-datamover-api/Dockerfile_victoria_centos
- kolla-ansible/trilio-datamover/Dockerfile_ussuri_centos
- kolla-ansible/trilio-datamover/Dockerfile_victoria_centos
- kolla-ansible/trilio-horizon-plugin/Dockerfile_ussuri_centos
- kolla-ansible/trilio-horizon-plugin/Dockerfile_victoria_centos
- redhat-director-scripts/docker/build_tripleo_containers.sh
@abhijeetpatra @savitha-afour @shyam-biradar could you please review this
> TVAULT-4880 Centos 8 EOL issue: yum is broken while running yum update

- redhat-director-scripts/docker/trilio-datamover/Dockerfile_rhosp16.1
- redhat-director-scripts/docker/trilio-datamover/Dockerfile_rhosp16.2
@abhijeetpatra @shyam-biradar could you please review this
> TVAULT-5119 RHOSP datamover base image change

- redhat-director-scripts/docker/trilio-datamover/Dockerfile_rhosp13
@abhijeetpatra @shyam-biradar could you please review this
> TVAULT-5151 [RHOSP13] datamover is failed to mount the NFS backup target

- kolla-ansible/ansible/roles/triliovault/tasks/config.yml
-- Validated deployment on NFS backup target
> TVAULT-5171 for 4.2 HF3   Fixed ownership issue 

- openstack-helm/triliovault/templates/nfs-pv.yaml
- openstack-helm/triliovault/templates/nfs-pvc.yaml
- openstack-helm/triliovault/utils/render_templates.sh
- openstack-helm/triliovault/values.yaml
- openstack-helm/triliovault/values_overrides/victoria-ubuntu_focal.yaml
-- Fixed both issues mentioned in jira TVAULT-5215
-- Tested deployment with multi-ip-nfs
-- Tested deployment with S3 target
-- Tested template rendering with nfs backup target
> TVAULT-5215

- redhat-director-scripts/docker/build_rhosp16_containers.sh
**Current changes**
1.  Add new param PUSH_PKG_CNT to provide flexibility of uploading/not uploading pkgs & containers.
> TVAULT-5219 : Backport coding improvements from dev-stable/5.0 to 4.1

- openstack-helm/triliovault/values.yaml
-- Validated deployment with nfs backup target
-- Tested backup
> INTEROP-615  Updated rabbitmq username and keystone username to 'workloadmgr'

- openstack-helm/triliovault/templates/deployment-wlm-workloads.yaml
-- Added /lib/modules mount on wlm-workloads pod
-- Validated deployment
> INTEROP-617 added lib modules mount

- openstack-helm/triliovault/values.yaml
-- Validated deployment and conf file changes
-- Validated horizon plugin deployment and horizon changes related to encryption.
> INTEROP-618 Added barbican section in triliovault-wlm.conf file

- ansible/create_cloud_admin_trust.yml
- ansible/environments/group_vars/all/vars.yml
- ansible/os-tvault-cloud-trust.yml
- ansible/roles/ansible-datamover-api/defaults/main.yml
- ansible/roles/ansible-datamover-api/templates/triliovault.list
- ansible/roles/ansible-datamover-api/templates/triliovault.repo
- ansible/roles/ansible-horizon-plugin/defaults/main.yml
- ansible/roles/ansible-horizon-plugin/templates/triliovault.list
- ansible/roles/ansible-horizon-plugin/templates/triliovault.repo
- ansible/roles/ansible-tvault-contego-extension/defaults/main.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/create_conf_dirs.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/install_ubuntu.yml
- ansible/roles/ansible-tvault-contego-extension/templates/triliovault.list
- ansible/roles/ansible-tvault-contego-extension/templates/triliovault.repo
- ansible/roles/openstack-ansible-os_triliovault_wlm/defaults/main.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/create_conf_dirs.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/install-centos.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/install-ubuntu.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/main.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/templates/triliovault-wlm.conf.j2
- ansible/roles/openstack-ansible-os_triliovault_wlm/templates/triliovault.list
- ansible/roles/openstack-ansible-os_triliovault_wlm/templates/triliovault.repo
- ansible/triliovault-common-files/triliovault_user_variables.yml
The job to create the configuration dirs for the tvault-contego service was missing.
Imported the task and validated it on OSA Wallaby Ubuntu 20.04 (multi-controller & compute node setup).
Deployment went fine.
`PLAY RECAP ************************************************************************************************************************************************************
compute1                   : ok=121  changed=50   unreachable=0    failed=0    skipped=5    rescued=0    ignored=2
compute2                   : ok=121  changed=50   unreachable=0    failed=0    skipped=5    rescued=0    ignored=2
controller1_dmapi_container-e96a1fc8 : ok=46   changed=22   unreachable=0    failed=0    skipped=9    rescued=0    ignored=1
controller1_horizon_container-63776d6c : ok=51   changed=25 …
> missed conf dir task missed fixes

- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/get_cloud_details.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/get_endpoint_list.yml
Deployment script creates triliovault-cloudrc at /root dir
Added localhost OS CA Cert File path under triliovault-cloudrc that required to fetch cloud details
> update correct path of OS CACert

- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/install-centos.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/install-ubuntu.yml
Task Names are updated and specified when services start.
> Removed duplicate task & updated task names

- kolla-ansible/ansible/roles/triliovault/defaults/main.yml
Updated the workloadmgr service name to '**TrilivaultWLM**' instead of **workloadmgr **
> INTEROP-684 Updaterkladmr servicename it should be TrilivaultWLM

- ansible/environments/group_vars/all/vars.yml
- ansible/roles/ansible-datamover-api/tasks/synchronize_dmapi_db.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/install-centos.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/install-ubuntu.yml
Taking the controller hostname as input on the same host wlm-cron services is starting.
> TVAULT-5351  Scheduler is triggering the multiple snapshots on all the controller nodes & TVAULT-5376-DMAPI DB Sync failed due to multiple runs

- openstack-helm/triliovault/values.yaml
- openstack-helm/triliovault/values_overrides/victoria-ubuntu_focal.yaml
-- Updated database scheme for wlm service
> TVAULT-5439

- ansible/roles/ansible-tvault-contego-extension/tasks/uninstall_rhel.yml
Added task to clean the cache while uninstalling tvault-contego packages.
> uninstall cache clean

- ansible/roles/openstack-ansible-os_triliovault_wlm/defaults/main.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/create_conf_dirs.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/install-centos.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/install-ubuntu.yml
- ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/uninstall_wlm_pckgs.yml
dir `/etc/triliovault-wlm` got created once we install the _workloadmgr_ package
Explicitly no need to create it, hence removed the code and validated it on OSA Wallaby Ubuntu 20.04 sanity is passed no issue we face till now.
> TVAULT-5512 [OSA] deployment failed with error object of type 'NoneTyType' has no len()" - stable/5.0

- ansible/environments/group_vars/all/vars.yml
- ansible/main-install.yml
- ansible/roles/ansible-tvault-contego-extension/tasks/nova_compute_filter_file.yml
- ansible/tvault_pre_install.yml
The purpose of this PR is to incorporate the changes made for the **4.2HF4** into the `dev-stable/5.0` branch
> INTEROP-829 Incorporate the DevOps fixes for 4.2HF4 into the dev-stable/5.0 cfg branch

- openstack-helm/triliovault/manifest.yaml
- openstack-helm/triliovault/templates/deployment-wlm-cron.yaml
- openstack-helm/triliovault/templates/deployment-wlm-scheduler.yaml
- openstack-helm/triliovault/templates/deployment-wlm-workloads.yaml
-- Removed all mounts of workloadmgr.conf. These are not required now.
> TVAULT-5268 Removed workloadmgr.conf

- openstack-helm/triliovault/templates/configmap-bin-datamover-api.yaml
- openstack-helm/triliovault/templates/configmap-bin-datamover.yaml
- openstack-helm/triliovault/templates/configmap-bin-wlm.yaml
- openstack-helm/triliovault/templates/configmap-etc-datamover-api.yaml
- openstack-helm/triliovault/templates/configmap-etc-datamover.yaml
- openstack-helm/triliovault/templates/configmap-etc-wlm.yaml
- openstack-helm/triliovault/templates/daemonset-datamover.yaml
- openstack-helm/triliovault/templates/deployment-datamover-api.yaml
- openstack-helm/triliovault/templates/deployment-wlm-api.yaml
- openstack-helm/triliovault/templates/deployment-wlm-cron.yaml
- openstack-helm/triliovault/templates/deployment-wlm-scheduler.yaml
- openstack-helm/triliovault/templates/deployment-wlm-workloads.yaml
- openstack-helm/triliovault/templates/job-datamover-bootstrap.yaml
- openstack-helm/triliovault/templates/job-datamover-db-drop.yaml
- openstack-helm/triliovault/templates/job-datamover-db-init.yaml
- openstack-helm/triliovault/templates/job-datamover-db-sync.yaml
- openstack-helm/triliovault/templates/job-datamover-ks-endpoints.yaml
- openstack-helm/triliovault/templates/job-datamover-ks-service.yaml
- openstack-helm/triliovault/templates/job-datamover-ks-user.yaml
- openstack-helm/triliovault/templates/job-image-repo-sync.yaml
- openstack-helm/triliovault/templates/job-wlm-bootstrap.yaml
- openstack-helm/triliovault/templates/job-wlm-cloud-trust.yaml
- openstack-helm/triliovault/templates/job-wlm-db-drop.yaml
- openstack-helm/triliovault/templates/job-wlm-db-init.yaml
- openstack-helm/triliovault/templates/job-wlm-db-sync.yaml
- openstack-helm/triliovault/templates/job-wlm-ks-endpoints.yaml
- openstack-helm/triliovault/templates/job-wlm-ks-service.yaml
- openstack-helm/triliovault/templates/job-wlm-ks-user.yaml
- openstack-helm/triliovault/templates/job-wlm-rabbit-init.yaml
- Created separate config maps for datamover api, datamover and wlm services.
- Now if user updates any parameter value of datamover conf, other service pods will not get restarted
- All jobs will get executed.
> TVAULT-5288

- redhat-director-scripts/rhosp16/services/triliovault-wlm-api.yaml
- redhat-director-scripts/rhosp16/services/triliovault-wlm-cron-pacemaker.yaml
- redhat-director-scripts/rhosp16/services/triliovault-wlm-scheduler.yaml
- redhat-director-scripts/rhosp16/services/triliovault-wlm-workloads.yaml
-- Added fix to existing code to populate cloud_unique_id parameter correctly in triliovault-wlm.conf file
> TVAULT-5615: Added fix to populate cloud_unique_id in wlm conf

- redhat-director-scripts/rhosp16.1/environments/trilio_datamover_opt_volumes.yaml
- redhat-director-scripts/rhosp16.1/services/trilio-datamover.yaml
- redhat-director-scripts/rhosp16.2/environments/trilio_datamover_opt_volumes.yaml
- redhat-director-scripts/rhosp16.2/services/trilio-datamover.yaml
--Added  a variable to pass extra volume mounts for datamover service.
> TVAULT-5621

- redhat-director-scripts/rhosp16.1/environments/trilio_datamover_opt_volumes.yaml
- redhat-director-scripts/rhosp16.1/services/trilio-datamover.yaml
- redhat-director-scripts/rhosp16.2/environments/trilio_datamover_opt_volumes.yaml
- redhat-director-scripts/rhosp16.2/services/trilio-datamover.yaml
> TVAULT-5621: Dev hotfix5/4.2

- tripleo-scripts/docker/trilio-datamover-api/trilio.repo
- tripleo-scripts/docker/trilio-datamover/trilio.repo
- tripleo-scripts/docker/trilio-horizon-plugin/trilio.repo
-- Removed rpm repo url, used a variable for it. {RPM_REPO_URL}
> TVAULT-5645:   Removing sensitive data

- openstack-helm/triliovault/utils/patch.yaml
- openstack-helm/triliovault/utils/uninstall.sh
-- Added code to clean pods and replicasets
> TVAULT-5689: Added fixes for uninstall script

- TVOAppliance/README
- TVOAppliance/hf_upgrade.sh
Changes validated through below job 
http://192.168.1.62:8080/job/TVO-Automation/job/Train/job/RHOSP_16_1_TLS_Multinode-2_Sanity/207/HTML_20Report/
@savitha-p @rajneeshkapoor Please review and merge
> Fixed the package dir name and added the DB upgrade step post upgrade

- TVOAppliance/hf_upgrade.sh
TVAULT-5718 : Perform DB upgrade only if TVO is already configured
> TVAULT-5718 : Perform DB upgrade only if TVO is already configured
