trilioData/triliovault-cfg-scripts

ansible/roles/ansible-tvault-contego-extension/tasks/ensure_data_dirs.yml, ansible/roles/ansible-tvault-contego-extension/tasks/set_virtenv.yml
TVAULT-2757:
**Issue** : tvault-contego pip package in not getting download and installed as ansible-template to download pip package and install it inside virtual env. is not getting called for queens setup.
**Fix**: added code so that ansible-template to download and install pip pakcage sholud get called for queens openstack release as well.
TVAULT-2750:  
**Fix**: added  code to provide nova user permissions to "/var/trliovault-mounts" dir.
@shyam-biradar , @abhijeetpatra , @MuralidharB , @rajneeshkapoor , @sachin-trilio Please review
=> Fixed TVAULT-2757

ansible/roles/ansible-datamover-api/tasks/install_on_queens.yml
**Issue** : apt ansible module was not able to install dmapi debian pacakge by default as package origin is not trusted one for a controller.
**Fix**: added "allow-unthenticated : yes" while install apt pacakages.
@shyam-biradar , @MuralidharB , @abhijeetpatra , @rajneeshkapoor , @sachin-trilio Please review
=> Fixed TVAULT-2762

ansible/roles/ansible-horizon-plugin/tasks/install.yml, ansible/roles/ansible-horizon-plugin/tasks/uninstall.yml, ansible/roles/ansible-tvault-contego-extension/tasks/contego_service.yml, ansible/roles/ansible-tvault-contego-extension/tasks/validate_obj_bkp.yml
1. added code to restart contego service twice. as on first restart contego service is failing in sometime.
2. added code to fix easy_install command failure issue(TVAULT-2731) . We have release noted this issue. but we need some fix here to avoid ansible tasks failures. 
@abhijeetpatra , @shyam-biradar  , @rajneeshkapoor , @sachin-trilio , @MuralidharB  Please review.
=> Fixed TVAULT-2676 and added ignore_errors to fix easy_install issue

juju-charms/charm-trilio-data-mover-api/src/reactive/dmapi_handlers.py
The DataMover API requires access to the nova database (not the dmapi
database).
Update handler to request access to the correct shared database and
drop provision of unit private address - the interface does the
right thing with regards to using network space binding of the
relation endpoint on the local charm unit.
=> Request access to nova database

ansible/roles/ansible-tvault-contego-extension/tasks/add_users.yml, ansible/roles/ansible-tvault-contego-extension/tasks/contego_service.yml, ansible/roles/ansible-tvault-contego-extension/tasks/set_virtenv.yml, ansible/roles/ansible-tvault-contego-extension/templates/contego_service.j2, ansible/roles/ansible-tvault-contego-extension/templates/contego_service_s3.j2, ansible/roles/ansible-tvault-contego-extension/templates/set_virt_newton_ubuntu.j2
Fixed following issues:
1.TVAULT-2755: Removed code to create cpu.shares files at "/sys/fs/cgroup/trilio/cpu/" 
2.TVAULT-2687: i.Removed nova users root access from soudeors file 
ii. Created seperate service template for NFS and object-store 
3.TVAULT-2756: Removed "After=opesntack-nova-compute" paramter from contego file
4.TVAULT-2699: Addeed code to download "newton_ubuntu" virtual env           
@MuralidharB, @amitkumar-a4 , @shyam-biradar , @abhijeetpatra , @rajneeshkapoor , @sachin-trilio Please review
=> accomodate all shell changes to ansible for 3.0

juju-charms/charm-trilio-horizon-plugin/src/reactive/trilio_horizon_plugin.py
It was determined that on some systems, the path to the workloads_admin
dashboards was /usr/local/lib and some others, /usr/lib, so this code
attempts to find the index.html file to be replaced and then sets the
dashboard_path for file replacement to that path, or reverts to original
setting.
=> Fixed the trilio-horizon-plugin.html index template path

juju-charms/charm-trilio-data-mover/src/reactive/trilio_data_mover.py, juju-charms/charm-trilio-data-mover/unit_tests/test_data_mover.py
1. Removed apt_upgrade from install
2. Updated Upgrade hook by checking existing contego packages and then removing those before installing new
=> Updated trilio-data-mover upgrade for moving from py2 to py3

ansible/roles/ansible-horizon-plugin/tasks/collect_compress.yml
=> TVAULT-3977:[OSA Ussuri ] Trilio Components deployment failed at Task 'Include vars of /tmp/connection_string into the 'tvault_vars' variable'

redhat-director-scripts/docker/services/trilio-datamover-api-osp16.yaml, redhat-director-scripts/docker/trilio-horizon-plugin/Dockerfile_rhosp16.1
-- Added manage.py fix in horizon dockerfile
-- Recreated and Published new containers to dockerhub with tag 4.0.115-rhosp16.1
-- Added fix for TVAULT-3811 in the same PR.
=> V4.0maintenance TVAULT-3968

kolla-ansible/trilio-datamover/Dockerfile_pike_ubuntu, kolla-ansible/trilio-datamover/Dockerfile_queens_ubuntu, kolla-ansible/trilio-datamover/Dockerfile_rocky_ubuntu, kolla-ansible/trilio-datamover/Dockerfile_stein_ubuntu, kolla-ansible/trilio-datamover/Dockerfile_train_ubuntu, kolla-ansible/trilio-datamover/Dockerfile_ussuri_ubuntu
Removed invalid step from Dockerfiles present for the Ubuntu platform.
=> [TVAULT-3989] Datamover container stuck in restarting state due to rootwrap.conf absent in datamover

common/nova_userid.sh
adding root:nova permission  "/etc/workloadmgr/tvault_key.pem"
=> TVAULT-4166: smtp server password is saved as plain text in wlm database - security breach 4.1

kolla-ansible/ansible/roles/triliovault/defaults/main.yml, kolla-ansible/ansible/roles/triliovault/templates/triliovault-datamover.conf.j2, kolla-ansible/ansible/roles/triliovault/templates/triliovault-datamover.json.j2, kolla-ansible/ansible/triliovault_globals.yml
Adde fix for the TVAULT-4118
Instead of ceph_s3 backup target for wasabi, we can specify in the globals.yml file other_s3_compatible for both that is ceph_s3 & wasabi_s3.
=> Fix For the TVAULT-4118

redhat-director-scripts/common/install_puppet_module.sh, redhat-director-scripts/common/trilio.repo, redhat-director-scripts/common/virt_commands
-- This script is capable of installing triliovault puppet module into overcloud full qcow2 image.
-- This is required to support scenarios like triliovault installation during cloud scale up and fresh cloud installations.
=> TVAULT-3389: Added script to instal triliovault puppet module in  overcloud qcow2

ansible/roles/ansible-tvault-contego-extension/tasks/install_rhel.yml, ansible/roles/ansible-tvault-contego-extension/tasks/install_ubuntu.yml, ansible/roles/ansible-tvault-contego-extension/templates/module-load-rbd.conf.j2
To load rbd module on compute node provided templates file and task to load on current session using ansible module called **modprobe**
=> TVAULT-4735 Load rbd module on compute node

ansible/roles/ansible-horizon-plugin/tasks/collect_compress.yml, ansible/roles/ansible-horizon-plugin/tasks/pre_tasks.yml
Updated task Get os_local_settings_path with specified horizon_virtual_env 
Added shell command to  _Find openstack-dashboard path in horizon container_ in pre_tasks.yml
Trilio components of build 4.2.29 installation and uninstallation are tested on OSA Victoria CentOS8 working fine.
=> Tvault 4749 

ansible/roles/ansible-horizon-plugin/tasks/post_install.yml
The issue is that **trilio.pth** is empty if we run the search local **sites-packages** library dir under the **Horizon venv** 
Hence **static files** load got failed and the **trilio-backup-admin** tab was not working.
The fixes are tested on OSA Victoria CentOS8 setup deployment working fine.
TVM and OpenStack configuration is done able to load all the files under [**trilio-backup-admin**] tab
=> TVAULT-4758 find local sites-packages library path and that can be added into trilio.pth file required to load trilio static files

ansible/roles/ansible-tvault-contego-extension/tasks/install_rhel.yml, ansible/roles/ansible-tvault-contego-extension/tasks/install_ubuntu.yml, ansible/roles/ansible-tvault-contego-extension/templates/modprobe-nbd.conf.j2, ansible/roles/ansible-tvault-contego-extension/templates/module-load-nbd.conf.j2
Creates 2 templates files called modprobe-nbd.conf.j2 and module-load-nbd.conf.j2 which are responsible for creating the conf files to load nbd after reboot of compute node(s)
and load the nbd module using ansible module modprobe
=> TVAULT-4710 standard code to load nbd driver

ansible/roles/ansible-horizon-plugin/tasks/collect_compress.yml
Enable OPENSTACK_ENCRYPTION_SUPPORT is enabled when key-manager(Barbican) Service is deployed  by-default it's disabled and TRILIO_ENCRYPTION_SUPPORT enable  except CentOS7
=> TVAULT-4669  Enable OPENSTACK_ENCRYPTION_SUPPORT & TRILIO_ENCRYPTION_SUPPORT when Barbican is deployed

ansible/roles/ansible-horizon-plugin/tasks/collect_compress.yml
The encryption check box was missing while creating the workloads.
Failed due to the data format was not dictionary.
Switched to dictionary format for horizon settings.
Previous values:
```
-    regexp: '^OPENSTACK_ENCRYPTION_SUPPORT'
line: OPENSTACK_ENCRYPTION_SUPPORT = {{ OPENSTACK_ENCRYPTION }}
-    regexp: '^TRILIO_ENCRYPTION_SUPPORT'
line: TRILIO_ENCRYPTION_SUPPORT = {{ TRILIO_ENCRYPTION }}
```
Updated values:
```
-     regexp: "^HORIZON_CONFIG\\['OPENSTACK_ENCRYPTION_SUPPORT'\\] "
line: HORIZON_CONFIG['OPENSTACK_ENCRYPTION_SUPPORT'] = {{ OPENSTACK_ENCRYPTION }}
-     regexp: "^HORIZON_CONFIG\\['TRILIO_ENCRYPTION_SUPPORT'\\] "
line: HORIZON_CONFIG['TRILIO_ENCRYPTION_SUPPORT'] = {{ TRILIO_ENCRYPTION }}
```
=> Tvault 4834 encryption checkbox is missing from workload create tab in UI in 4.2.43

redhat-director-scripts/docker/build_rhosp16_containers.sh
Add RHOSP_16.2 Containers to build automation support Triliovault 4.2
build_rhosp16_containers.sh script will add RHOSP16.1 and 16.2 containers
=> Tvault 4858 Add RHOSP_16.2 Containers to build automation support Triliovault 4.2

redhat-director-scripts/docker/build_rhosp16_containers.sh
Add RHOSP16.2 Containers creation code for support Triliovault 4.2 onward
Dropped support for RHOSP 16 from Triliovault 4.2 onward
=> TVAULT-4858 ADD RHOSP 16.2 CONTAINER CREATION STEPS INTO TRILIO CFG SCRIPT

kolla-ansible/trilio-datamover-api/Dockerfile_victoria_centos, kolla-ansible/trilio-datamover/Dockerfile_victoria_centos, kolla-ansible/trilio-horizon-plugin/Dockerfile_victoria_centos
@abhijeetpatra @rajneeshkapoor @shyam-biradar could you please review this 
Commenting mirrorlist as the CentOS8 has reached EOF.
CentOS8 repos have been moved from http://mirror.centos.org to http://vault.centos.org by  CentOS authorities.
=> TVAULT-4880 Centos 8 EOL issue: yum is broken while running yum update

ansible/roles/ansible-datamover-api/tasks/get_python.yml
`which` cmd is not working into the datamover API containers hence we have replaced the which cmd to `type -p `
=> TVAULT-4869 Triliovault datamover api service deployment is failing due to which cmd is not working

ansible/environments/group_vars/all/vars.yml, ansible/roles/ansible-horizon-plugin/tasks/collect_compress.yml, ansible/roles/ansible-horizon-plugin/tasks/find_manage_file.yml, ansible/roles/ansible-horizon-plugin/tasks/pre_tasks.yml
Added code changes to install the `findutils` package which is not present in the OSA Wallaby Horizon containers, which required to run some find commands which are present into the get_venv.yml
=> TVAULT-4883 & TL-33 Failed to deploy Horizon Plugin in OSA WALLABY

ansible/roles/ansible-datamover-api/tasks/get_python.yml
To fetch the current running python path we were running the _type -p python<version>_ with Ansible shell module.
Shell modules run the commands under /bin/sh ansible was activating the /bin/sh shell if we run the _type -p python<version>_
It was showing the **-p not found** and instead of the path of python comes with the **_python3 is_** 
Due to this  [TASK] find location when using python<version>  was failing
Updated code to check the currently which python were uses bash /bin/bash 
```
grroot@controller:~# lxc-ls | grep dmapi
controller_dmapi_container-6fff6daf          controller_galera_container-a868fba1
root@controller:~# lxc-attach -n controller_dmapi_container-6fff6daf
root@controller-dmapi-container-6fff6daf:~# type -p python3
/usr/bin/python3 …
```
=> TVAULT-4930 Failed to deploy DMAPI service type -p command running was running in /bin/sh was wrong

redhat-director-scripts/tripleo-wallaby/services/trilio-datamover.yaml
**Change log document:**
https://triliodata.atlassian.net/wiki/spaces/TL/pages/3411148801/TVAULT-4938+Add+ipc+host+parameter+to+tripleo+wallaby
=> TVAULT-4938: Added ipc:host parameter to datamover container wallaby

redhat-director-scripts/tripleo-wallaby/services/trilio-datamover.yaml
**Change Log:**
https://triliodata.atlassian.net/wiki/spaces/TL/pages/3414720513/TVAULT-4946+Overcloud+deploy+failing+on+tripleo+wallaby
=> TVAULT-4946: Update ceph and iscsi mounts for trilio datamover container

openstack-helm/triliovault/values.yaml
- The containers are now running with nova user with correct groups:
```
root@moskautomation1:/opt/triliovault-cfg-scripts/openstack-helm/triliovault# kubectl exec -it triliovault-datamover-openstack-compute-node-fzqrb -- id
Defaulted container "triliovault-datamover" out of: triliovault-datamover, init (init), triliovault-datamover-init (init), ceph-keyring-placement-triliovault (init)
uid=42424(nova) gid=42424(nova) groups=42424(nova),6(disk),113(kvm),115(libvirt)
root@moskautomation1:/opt/triliovault-cfg-scripts/openstack-helm/triliovault#
```
- Encrypted Snapshots and restores are successful
=> TVAULT-5096: running the container with specific group fails encrypted snapshot creation

ansible/roles/ansible-tvault-contego-extension/tasks/install_rhel.yml, ansible/roles/ansible-tvault-contego-extension/tasks/install_ubuntu.yml, ansible/roles/ansible-tvault-contego-extension/tasks/post_install.yml, ansible/roles/ansible-tvault-contego-extension/tasks/uninstall_rhel.yml, ansible/roles/ansible-tvault-contego-extension/tasks/uninstall_ubuntu.yml
Code cleanup.
Not required to deploy the contego & puppet-triliovault packages.
=> TVAULT-5010 Cleanup contego venv dependency from the datamover packages

kolla-ansible/ansible/roles/triliovault/tasks/config.yml
-- Validated deployment with NFS and s3 backup target
=> TVAULT-5171 fix for 4.1 HF3 -- Fixed ownership issue for triliovault-mounts dir

ansible/roles/ansible-datamover-api/tasks/db_setup_ussuri.yml, ansible/roles/ansible-datamover-api/tasks/db_setup_victoria.yml, ansible/roles/ansible-datamover-api/templates/datamover_url, ansible/roles/ansible-tvault-contego-extension/templates/tvault-contego.conf.j2, ansible/roles/ansible-tvault-contego-extension/templates/tvault-object-store.conf.j2, ansible/roles/openstack-ansible-os_triliovault_wlm/templates/triliovault-object-store.conf.j2, ansible/roles/openstack-ansible-os_triliovault_wlm/templates/triliovault-wlm.conf.j2
In the configuration file under the default section log_config option has been used, it's deprecated.
So we need to use log_config_append instead of log_config
=> TVAULT-5321 Tvault 5.0 Deployment Failed due to deprecated option log_config uses instead of log_config_append

ansible/environments/group_vars/all/vars.yml, ansible/roles/openstack-ansible-os_triliovault_wlm/tasks/triliovault_db_sync.yml, ansible/roles/openstack-ansible-os_triliovault_wlm/templates/triliovault-object-store.conf.j2, ansible/roles/openstack-ansible-os_triliovault_wlm/templates/triliovault-wlm.conf.j2
- Additional fix: In HA env, db sync cmd should run only once, running on all nodes will fail.
- Additional fix: Default values are set for S3 signature and auth versions
=> TVAULT-5336: Mysql connection issue if the driver is not set to pymysql

ansible/roles/ansible-tvault-contego-extension/tasks/install_rhel.yml
RPM package of S3 fuse plugin was miss-spelled in install task
=> TVAULT-5338 RPM Based S3 Fuse Plugin Name was miss-spelled in install task

ansible/roles/ansible-tvault-contego-extension/defaults/main.yml, ansible/roles/openstack-ansible-os_triliovault_wlm/defaults/main.yml
corrected the triliovault mount dir from **/var/trilio/triliovault-mounts** to **/var/triliovault-mounts**
=> TVAULT-5420 mount dir should be insync with 4.2 build

ansible/environments/group_vars/all/vars.yml, ansible/roles/ansible-tvault-contego-extension/tasks/nova_compute_filter_file.yml
Need to specify the **nova_virtual_env** under _/etc/openstack_deploy/user_tvault_vars.yml_ if more than one nova virtual environment is present on compute node.
The  default value of **nova_virtual_env** is '/openstack/venvs/nova*'
=> TVAULT-5328 Failed ansible-tvault-contego-extension : create trilio.filters for mount and unmount task

ansible/roles/openstack-ansible-os_triliovault_wlm/defaults/main.yml, ansible/roles/openstack-ansible-os_triliovault_wlm/templates/triliovault-wlm.conf.j2
Removed the taskflow_max_age variable from the trilioault-wlm.conf file
=> TVAULT-5505 OSA remove taskflow_max_age variable from triliovault-wlm.conf  templates

ansible/environments/group_vars/all/vars.yml, ansible/roles/ansible-tvault-contego-extension/tasks/nova_compute_filter_file.yml
with venv_tag we are fetching the value that had set into the ansible_facts, it should be equivalent to the DISTRIB_RELEASE  of Openstack which resides under /etc/openstack-release
=> improvement TVAULT-5328 Nova virtual env with venv_tag

ansible/environments/group_vars/all/vars.yml
No need to set the value of TVAULT_PACKAGE_VERSION, it's default value should be '4.2.64'
=> INTEROP-805 Set default value of TVAULT_PACKAGE_VERSION for OSA

kolla-ansible/ansible/roles/triliovault/tasks/config.yml
The change ensures the dirs `/var/trilio` and` /var/trilio/triliovault-mounts` is present and owner is `nova:nova`
=> Set nova:nova ownership to the mount dir under wlm & datamover container 

ansible/tvault_pre_install.yml
with this playbook, the user is able to install the lxc packages under OSA  centos and ubuntu setups.
Validated the deployment on the OSA Wallaby CentOS 8 Stream  & Ubuntu 20.04
OSA Wallaby CentOS 8 Stream deploy logs
`  },
"msg": "",
"rc": 0,
"results": [
"Installed: python3-lxc-3.0.4-2.el8.x86_64",
"Installed: lxc-templates-3.0.4-2.el8.x86_64"
]
}
META: ran handlers
META: ran handlers
PLAY RECAP ***********************************************************************************************************************************************************
localhost                  : ok=4    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
EXIT NOTICE [Playbook execution success] **************************************`
OSA Wallaby Ubuntu 20.04 
` "Preparing to …
=> TVAULT-5325 Install the pre-requisite lxc packages 

ansible/roles/ansible-tvault-contego-extension/tasks/nfs.yml
By default on compute node, it is taking NFS version 4 which we do not support 
we need to set nfsvers=3  like 'nolock,soft,timeo=180,intr,lookupcache=none,nfsvers=3'****
=> TVAULT-5546 snapshot and restore failing intermittently because of nfsvers=3

kolla-ansible/ansible/roles/triliovault/defaults/main.yml
updated trilio-wlm container image
`---> OLD
triliovault_wlm_image: "{{ triliovault_docker_registry }}/trilio/{{ kolla_base_distro }}-binary-trilio-wlm:{{ triliovault_wlm_tag }}"
e.g.
docker.io/trilio/centos-binary-trilio-wlm:5.0.SB-wallaby
---> NEW
triliovault_wlm_image: "{{ triliovault_docker_registry }}/trilio/kolla-{{ kolla_base_distro }}-trilio-wlm:{{ triliovault_wlm_tag }}"
e.g.
docker.io/trilio/kolla-centos-trilio-wlm:5.0.SB-wallaby`
=> INTEROP-806 Incorporate the repo changes in DevOps code of Kolla-Ansible
